// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"time"
)

type Email struct {
	ID    int64  `json:"id"`
	Title string `json:"title"`
	// Content of the post
	Body      string    `json:"body"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
}

type Transaction struct {
	ID        int64     `json:"id"`
	EmailID   int64     `json:"email_id"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
}
