// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"context"
)

type Querier interface {
	CreateEmail(ctx context.Context, arg CreateEmailParams) (Email, error)
	DeleteBook(ctx context.Context, id int64) error
	GetEmail(ctx context.Context, id int64) (Email, error)
	ListEmails(ctx context.Context, arg ListEmailsParams) ([]Email, error)
	UpdateEmail(ctx context.Context, arg UpdateEmailParams) (Email, error)
}

var _ Querier = (*Queries)(nil)
